/* 
       e                   888 ,e,                 e88~~\                                     
      d8b     888-~\  e88~\888  "  Y88b  /        d888     888-~\  e88~-_  888  888 888-~88e  
     /Y88b    888    d888  888 888  Y88b/         8888 __  888    d888   i 888  888 888  888b 
    /  Y88b   888    8888  888 888   Y88b         8888   | 888    8888   | 888  888 888  8888 
   /____Y88b  888    Y888  888 888   /Y88b        Y888   | 888    Y888   ' 888  888 888  888P 
  /      Y88b 888     "88_/888 888  /  Y88b        "88__/  888     "88_-~  "88_-888 888-_88"  
  📣 Version BETA - Xlator & SkyX [ID FR] - Copyright© 2023                         88   
.
*/

import { useEffect, useState } from "react";
import { getStorage, ref, deleteObject } from "firebase/storage";
import { logout, useAuth, upload } from "../config/FirebaseConfig.js";
import Head from 'next/head';
import { useRouter } from 'next/navigation';
import UnknowPage from '../404.js';
import $ from 'jquery';

export default function Profile() {
    const storage = getStorage();
    const { push } = useRouter();
    const currentUser = useAuth();
    const [photo, setPhoto] = useState(null);
    const [loading, setLoading] = useState(false);
    const [photoURL, setPhotoURL] = useState("https://images.nightcafe.studio//assets/profile.png");
    const [error, setError] = useState(false);

    if (typeof document !== 'undefined') {
        $( document ).ready(function() {
            $("#new-content").css("display", "none").hide();
      
            $('#personnal_settings').click(function() {
            $("#current-content").animate({
                opacity: 0
            }, 350, function() {
                $("#new-content").css("opacity", 1).fadeIn(300);
                $('#current-content').hide();
                $(".popup-content").animate({
                    width: "500"
                }, 300 );
            });
            });
        
            $('#back_button').click(function() {
            $("#new-content").animate({
                opacity: 0
            }, 350, function() {
                $("#current-content").css("opacity", 1).fadeIn(300);
                $("#new-content").hide();
                $(".popup-content").animate({
                    width: "350"
                }, 300 );
            });
            });
        });
    }      

    /* ✨ The source link of the image of the user profile picture was replaced by the one of the actual Firebase's Database : ✨ */
    useEffect(() => { 
        if (currentUser?.photoURL) { setPhotoURL(currentUser.photoURL); }  
    }, [currentUser]);

    /* 📦 Referring to the upload file functions : 📦 */
    function UploadNewPicturePush() { 
        upload(photo, currentUser, setLoading); 
        $("#current-content").animate({
            opacity: 0
          }, 10, function() {
            $("#new-content").css("opacity", 1).show();
        });
    }

    function UploadNewPictureChange(e) {
        const reader = new FileReader();
        reader.onload = (event) => {
            document.getElementById("profile_pic").src = event.target.result;
        }

        reader.readAsDataURL(e.target.files[0]);
        if (e.target.files[0]) { setPhoto(e.target.files[0]) }; 

        $("#current-content").animate({
            opacity: 0
          }, 10, function() {
            $("#new-content").css("opacity", 1).show();
        });
    }

    /* 💨 Simple function to Logout the actual user (in browser cookies) : 💨 */
    async function Logout() {
        setLoading(true);
        try {
          await logout();
        } catch {
          alert("Error!");
        }
        setLoading(false);
        push('/');
    }

    /* 🔴 Function to remove the actual user profile picture : 🔴 */
    function RemovePhoto() {
        const desertRef = ref(storage, photoURL);
        if (currentUser?.photoURL) {
            deleteObject(desertRef).then(() => {
                alert("Ta photo a bien été supprimé ! 👋");
                window.location.reload();
            })
        } else {
            alert("On ne peut pas supprimer ta photo de profil : tu en as pas ! Mets en une et on verra après ! 🧐")
        }
    }

    return (
        <>
            <Head>
                <title>Home • Ardix Group</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="https://zupimages.net/up/23/13/vzzn.png"/>
            </Head>

            {!currentUser && <UnknowPage/>}
            {currentUser && 
                <>
                    <div id="main_box">
                        <p className="connected_status">✔ Connected to 187.18.131.19, server in France.</p>

                        <div className="navbar">
                            <img className="app_logo" src="https://zupimages.net/up/23/13/vzzn.png" title="Ardix Group&copy; • Logo"/>
                            {error ? (
                                <a href="#user_popup">
                                    <div className="icon_arrow"><svg viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"></polyline></svg></div>
                                    <img src="https://images.nightcafe.studio//assets/profile.png" alt="avatar" onError={() => setError(true)} className="avatar"/>
                                </a>
                            ) : (
                                <a href="#user_popup">
                                    <div className="icon_arrow"><svg viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"></polyline></svg></div>
                                    <img style={{objectFit: "cover"}} src={photoURL} alt="avatar" onError={() => setError(true)} className="avatar"/>
                                </a>
                            )}

                            <div id="user_popup" className="popup-container">
                                <div className="popup-content">
                                    <a href="#" className="close">&times;</a>

                                    <div className="infos-box">
                                        <div className="content" id="current-content">
                                            <div className="image-container">
                                                {error ? (
                                                <img src="https://images.nightcafe.studio//assets/profile.png" alt="avatar" onError={() => setError(true)} className="user_pic"/>
                                                ) : (
                                                    <img style={{objectFit: "cover"}} src={photoURL} alt="avatar" onError={() => setError(true)} className="user_pic"/>
                                                )}
                                                <img className="circle-image" src="https://www.kataliz.fr/wp-content/uploads/2016/03/rond-blanc.png"/>
                                                <img className="verif_tag_img" src="https://cdn-icons-png.flaticon.com/512/1828/1828640.png" alt="verif_tag_img"/> 
                                            </div>

                                            <h1>{currentUser.displayName}</h1>
                                            <span>Id : {currentUser.uid}</span>

                                            <div className="followers_count" title="Ces chiffres sont (pour l'instant) tous fictifs ! ⛔">
                                                <div className="item"><h1>0</h1><p>Followers</p></div>
                                                <div className="item"><h1>0</h1><p>Posts</p></div>
                                            </div>  
                                            <button className="menu_button">
                                                <svg strokeLinecap="round" strokeLinejoin="round" className="icon"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><polyline points="17 11 19 13 23 9"></polyline></svg>
                                                <p className="text">View my profile page</p>
                                            </button>
                                            <button id="personnal_settings" className="menu_button">
                                                <svg strokeLinecap="round" strokeLinejoin="round" className="icon"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>
                                                <p className="text">Personnal settings</p>
                                            </button>
                                            <button disabled={loading} onClick={Logout} className="menu_button">
                                                <svg className="icon" viewBox="0 0 24 24" troke-linecap="round" strokeLinejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
                                                <p className="text">Logout</p>
                                            </button>
                                        </div>

                                        <div id="new-content">
                                            <div className="avatar_box">
                                                {error ? (
                                                    <img src="https://images.nightcafe.studio//assets/profile.png" alt="avatar" onError={() => setError(true)} id="profile_pic"/>
                                                ) : (
                                                    <img style={{objectFit: "cover"}} src={photoURL} alt="avatar" onError={() => setError(true)} id="profile_pic"/>
                                                )}
                                                <div className="pic_icon"><img src="https://cdn-icons-png.flaticon.com/512/158/158715.png"/></div>
                                            </div>

                                            <input type="file" accept=".jpg,.png,.jpeg" name="file" id="file" className="upload_new_picture" onChange={UploadNewPictureChange}/>
                                            <label htmlFor="file">Choose a new user picture ! 📸</label><br/><br/>

                                            <button className="menu_button" id="confirm_button" disabled={loading || !photo} onClick={UploadNewPicturePush}>
                                                <svg strokeLinecap="round" strokeLinejoin="round" className="icon"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="17 8 12 3 7 8"></polyline><line x1="12" y1="3" x2="12" y2="15"></line></svg>
                                                <p className="text">Confirm your new picture...</p>
                                            </button>

                                            <button className="menu_button" onClick={RemovePhoto}>
                                                <svg strokeLinecap="round" stroke="red" strokeLinejoin="round" className="icon"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                                                <p className="text"><font color="red">Remove your profile picture !</font></p>
                                            </button>
                                            
                                            <button id="back_button" className="menu_button">
                                                <svg strokeLinecap="round" strokeLinejoin="round" className="icon"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>
                                                <p className="text">Back to user's menu !</p>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* <div className="news_feed">
                            <p>• Ici, un <i>news feed</i> connecté au bot disponible plus tard sur le serveur Discord Officiel ! 👋</p>
                            <p>• Avec le suivi des logs les + importants du serveur Discord Officiel... 📋</p>
                        </div>

                        <div className="content_box">
                            <p>• Ici, sera afficher tous les posts récents sous forme d'un fil d'actu avec un infinity-scrolling ! 😎</p>
                        </div> */}
                    </div>
                </>
            }
        </>
    )
}