/* 
       e                   888 ,e,                 e88~~\                                     
      d8b     888-~\  e88~\888  "  Y88b  /        d888     888-~\  e88~-_  888  888 888-~88e  
     /Y88b    888    d888  888 888  Y88b/         8888 __  888    d888   i 888  888 888  888b 
    /  Y88b   888    8888  888 888   Y88b         8888   | 888    8888   | 888  888 888  8888 
   /____Y88b  888    Y888  888 888   /Y88b        Y888   | 888    Y888   ' 888  888 888  888P 
  /      Y88b 888     "88_/888 888  /  Y88b        "88__/  888     "88_-~  "88_-888 888-_88"  
  📣 Version BETA - Xlator & SkyX [ID FR] - Copyright© 2023                         88   
.
*/

import { useEffect, useState } from "react";
import { getStorage, ref, deleteObject } from "firebase/storage";
import { logout, useAuth, upload } from "../config/FirebaseConfig.js";
import Head from 'next/head';
import { useRouter } from 'next/navigation';
import UnknowPage from '../404.js';
import $ from 'jquery';

export default function Profile() {
    const storage = getStorage();
    const { push } = useRouter();
    const currentUser = useAuth();
    const [photo, setPhoto] = useState(null);
    const [loading, setLoading] = useState(false);
    const [photoURL, setPhotoURL] = useState("https://images.nightcafe.studio//assets/profile.png");
    const [error, setError] = useState(false);

    if (typeof document !== 'undefined') {
        $("#new-content").css("opacity", 0).hide();
      
        $('#personnal_settings').click(function() {
          $("#current-content").animate({
            opacity: 0
          }, 350, function() {
            $("#new-content").css("opacity", 1).fadeIn(300);
            $('#current-content').hide();
          });
        });
      
        $('#change-content-button2').click(function() {
          $("#new-content").animate({
            opacity: 0
          }, 350, function() {
            $("#current-content").css("opacity", 1).fadeIn(300);
            $("#new-content").hide();
          });
        });
    }      

    /* ✨ The source link of the image of the user profile picture was replaced by the one of the actual Firebase's Database : ✨ */
    useEffect(() => { 
        if (currentUser?.photoURL) { setPhotoURL(currentUser.photoURL); }  
    }, [currentUser]);

    /* 📦 Referring to the upload file functions : 📦 */
    function UploadNewPicturePush() { upload(photo, currentUser, setLoading); }
    function UploadNewPictureChange(e) {
        if (e.target.files[0]) {
            setPhoto(e.target.files[0]);
        } 
    }

    /* 💨 Simple function to Logout the actual user (in browser cookies) : 💨 */
    async function Logout() {
        setLoading(true);
        try {
          await logout();
        } catch {
          alert("Error!");
        }
        setLoading(false);
        push('/');
    }

    /* 🔴 Function to remove the actual user profile picture : 🔴 */
    function RemovePhoto() {
        const desertRef = ref(storage, photoURL);
        if (currentUser?.photoURL) {
            deleteObject(desertRef).then(() => {
                alert("Ta photo a bien été supprimé !");
                window.location.reload();
            })
        } else {
            alert("On peut pas supprimer ta photo de profil, tu en as pas ! Mets en une et on verra après !")
        }
    }

    return (
        <>
            <Head>
                <title>Home • Ardix</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="https://zupimages.net/up/23/13/vzzn.png"/>
            </Head>

            {!currentUser && <UnknowPage/>}
            {currentUser && 
                <>
                    {/* <div>
                        <input type="file" onChange={UploadNewPictureChange}/>
                        <button disabled={loading || !photo} onClick={UploadNewPicturePush}>Upload</button>
                        <button onClick={RemovePhoto}>Remove your photo</button>
                        {error ? (
                            <img src="https://images.nightcafe.studio//assets/profile.png" alt="avatar" onError={() => setError(true)} className="avatar"/>
                        ) : (
                            <img width="150px" height="160px" style={{objectFit: "cover"}} src={photoURL} alt="avatar" onError={() => setError(true)} className="avatar"/>
                        )}

                        <button disabled={loading} onClick={Logout}>Log Out</button>
                    </div> */}

                    <div id="main_box">
                        <div className="navbar">
                            <img className="app_logo" src="https://zupimages.net/up/23/13/vzzn.png" alt="logo"/>
                            {error ? (
                                <a href="#user_popup"><img src="https://images.nightcafe.studio//assets/profile.png" alt="avatar" onError={() => setError(true)} className="avatar"/></a>
                            ) : (
                                <a href="#user_popup"><img style={{objectFit: "cover"}} src={photoURL} alt="avatar" onError={() => setError(true)} className="avatar"/></a>
                            )}

                            {/* 📦 Action Icon Bar : 📦 */}
                            <div className="top_action_bar">
                                <p title="Boîte de réception !"><svg viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" className="feather-message-circle"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path></svg></p>
                                <p title="Centre des notifications..."><svg viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" className="feather-bell"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.73 21a2 2 0 0 1-3.46 0"></path></svg></p>
                                <p title="Recherchez quelque chose !"><svg viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" className="feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg></p>
                            </div>

                            <div id="user_popup" className="popup-container">
                                <div className="popup-content">
                                    <a href="#" className="close">&times;</a>

                                    <div className="infos-box">
                                        <div className="content" id="current-content">
                                            <div class="image-container">
                                                {error ? (
                                                <img src="https://images.nightcafe.studio//assets/profile.png" alt="avatar" onError={() => setError(true)} className="user_pic"/>
                                                ) : (
                                                    <img style={{objectFit: "cover"}} src={photoURL} alt="avatar" onError={() => setError(true)} className="user_pic"/>
                                                )}
                                                <img className="circle-image" src="https://www.kataliz.fr/wp-content/uploads/2016/03/rond-blanc.png"/>
                                                <img className="verif_tag_img" src="https://cdn-icons-png.flaticon.com/512/1828/1828640.png" alt="verif_tag_img"/> 
                                            </div>

                                            <h1>{currentUser.displayName}</h1>
                                            <span>Id : {currentUser.uid}</span>

                                            <div className="followers_count" title="Ces chiffres sont p(our l'instant) tous fictifs ! ⛔">
                                                <div className="item"><h1>12.5 K</h1><p>Followers</p></div>
                                                <div className="item"><h1>20</h1><p>Posts</p></div>
                                            </div>
                                            <button class="menu_button">
                                                <svg stroke-linecap="round" stroke-linejoin="round" class="icon"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
                                                <p className="text">My favorite posts</p>
                                            </button>
                                            <button id="personnal_settings" class="menu_button">
                                                <svg stroke-linecap="round" stroke-linejoin="round" class="icon"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>
                                                <p className="text">Personnal settings</p>
                                            </button>
                                            <button disabled={loading} onClick={Logout} class="menu_button">
                                                <svg className="icon" viewBox="0 0 24 24" troke-linecap="round" stroke-linejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
                                                <p className="text">Logout</p>
                                            </button>
                                        </div>

                                        <div id="new-content">
                                            <p>coucou</p><br/><br/>
                                            <button id="change-content-button2" class="menu_button">
                                                <svg stroke-linecap="round" stroke-linejoin="round" class="icon"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>
                                                <p className="text">Back to user's menu !</p>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* <div className="news_feed">
                            <p>• Ici, un <i>news feed</i> connecté au bot disponible plus tard sur le serveur Discord Officiel ! 👋</p>
                            <p>• Avec le suivi des logs les + importants du serveur Discord Officiel... 📋</p>
                        </div>

                        <div className="content_box">
                            <p>• Ici, sera afficher tous les posts récents sous forme d'un fil d'actu avec un infinity-scrolling ! 😎</p>
                        </div> */}
                    </div>
                </>
            }
        </>
    )
}