/* 
       e                   888 ,e,                 e88~~\                                     
      d8b     888-~\  e88~\888  "  Y88b  /        d888     888-~\  e88~-_  888  888 888-~88e  
     /Y88b    888    d888  888 888  Y88b/         8888 __  888    d888   i 888  888 888  888b 
    /  Y88b   888    8888  888 888   Y88b         8888   | 888    8888   | 888  888 888  8888 
   /____Y88b  888    Y888  888 888   /Y88b        Y888   | 888    Y888   ' 888  888 888  888P 
  /      Y88b 888     "88_/888 888  /  Y88b        "88__/  888     "88_-~  "88_-888 888-_88"  
  📣 Version BETA - Xlator & SkyX [ID FR] - Copyright© 2023                         88   
.
*/

import { useRef, useState } from "react";
import { signup, login, useAuth } from "./config/FirebaseConfig.js";
import Head from 'next/head';
import { useRouter } from 'next/navigation';

export default function Home() {
  const { push } = useRouter();
  const [ loading, setLoading ] = useState(false);
  const currentUser = useAuth();
  if (currentUser) { push('/home'); }

  const emailRefLogin = useRef();
  const passwordRefLogin = useRef();
  const emailRefSignup = useRef();
  const passwordRefSignup = useRef();
  const nameRefSignup = useRef();

  async function handleSignup() {
    setLoading(true);
    try {
      await signup(emailRefSignup.current.value, passwordRefSignup.current.value, nameRefSignup.current.value);
    } catch {
      alert("Error!");
    }
    setLoading(false);
  }

  async function handleLogin() {
    setLoading(true);
    try {
      await login(emailRefLogin.current.value, passwordRefLogin.current.value);
    } catch {
      alert("Error!");
    }
    setLoading(false);
  }

  return (
    <>
      <Head>
        <title>INDEX SOURCE</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <h1>Login :</h1>
      <input ref={emailRefLogin} placeholder="Email"/>
      <input ref={passwordRefLogin} type="password" placeholder="Password"/>
      <button disabled={loading} onClick={handleLogin}>Log In</button>

      <h1>Signup :</h1>
      <input ref={emailRefSignup} placeholder="Email"/>
      {/* <input ref={nameRefSignup} placeholder="Name"/> */}
      <input ref={passwordRefSignup} type="password" placeholder="Password"/>
      <button disabled={loading} onClick={handleSignup}>Sign Up</button>
    </>
  )
}
