/* 
       e                   888 ,e,                 e88~~\                                     
      d8b     888-~\  e88~\888  "  Y88b  /        d888     888-~\  e88~-_  888  888 888-~88e  
     /Y88b    888    d888  888 888  Y88b/         8888 __  888    d888   i 888  888 888  888b 
    /  Y88b   888    8888  888 888   Y88b         8888   | 888    8888   | 888  888 888  8888 
   /____Y88b  888    Y888  888 888   /Y88b        Y888   | 888    Y888   ' 888  888 888  888P 
  /      Y88b 888     "88_/888 888  /  Y88b        "88__/  888     "88_-~  "88_-888 888-_88"  
  📣 Version BETA - Xlator & SkyX [ID FR] - Copyright© 2023                         88   
.
*/

import Head from 'next/head';
import LinearProgress from '@mui/material/LinearProgress';

export default function LoadingPage() {
    return (
        <>
            <Head>
                <title>Loading... • Ardix Group&copy;</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="https://zupimages.net/up/23/13/vzzn.png"/>
            </Head>

            <div className='page_container'>
                <div className='loading_container'>
                    <img src="https://zupimages.net/up/23/13/vzzn.png" alt='logo_app'/>
                    <LinearProgress className='linear_progress'/>
                </div>
            </div>
        </>
    )
}