/* 
       e                   888 ,e,                 e88~~\                                     
      d8b     888-~\  e88~\888  "  Y88b  /        d888     888-~\  e88~-_  888  888 888-~88e  
     /Y88b    888    d888  888 888  Y88b/         8888 __  888    d888   i 888  888 888  888b 
    /  Y88b   888    8888  888 888   Y88b         8888   | 888    8888   | 888  888 888  8888 
   /____Y88b  888    Y888  888 888   /Y88b        Y888   | 888    Y888   ' 888  888 888  888P 
  /      Y88b 888     "88_/888 888  /  Y88b        "88__/  888     "88_-~  "88_-888 888-_88"  
  📣 Version BETA - Xlator & SkyX [ID FR] - Copyright© 2023                         88   
.
*/

import NavBar from "../../components/NavBar";
import { useEffect, useState } from "react";
import { useAuth } from "../../config/FirebaseConfig.js";
import Head from 'next/head';
import LoadingPage from "../LoadingPage.js";
import axios from 'axios';

export default function HomePage() {
    const currentUser = useAuth();
    const [data, setData] = useState(null);
    /* ✨ Read test all data in the collection name indicated : ✨ */
    useEffect(() => {
        const getAllPost = async () => {
          try {
            const response = await axios.get('/api/get_post');
            setData(response.data);
          } catch (error) {
            console.error(error);
          }
        };
    
        getAllPost();
    }, []);

    return (
        <>
            <Head>
                <title>Home • Ardix Group&copy;</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="https://zupimages.net/up/23/13/vzzn.png"/>
            </Head>

            {!currentUser && <LoadingPage/>}
            {currentUser && (
                <>
                    <div id="main_box">
                        <p className="connected_status">✔ Connected to 187.18.131.19, server in France.</p>
                        <NavBar/>

                        <div id="content_part">
                            {data && data.map((item, index) => (
                                <div className="showing_box" key={index}>
                                    <svg className="more_svg" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="1"></circle><circle cx="12" cy="5" r="1"></circle><circle cx="12" cy="19" r="1"></circle></svg>
                                    <h1 className="post_title">{item.title}</h1>
                                    <p className="post_description">{item.description}</p><br/>

                                    <div className="img_list">
                                        {item.images_uploaded.map((imageUrl, imageIndex) => (
                                            <img src={imageUrl} key={imageIndex}/>
                                        ))}
                                    </div>

                                    <div className="authors_info">
                                        <img src={item.authors_img} alt="Authors IMG"/>
                                        <h3>{item.authors_name}</h3><br/>
                                        <p className="info_span">This user is one of the first to join the platform ! ✨</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </>
            )}
        </>
    )
}